spring:
  datasource:
    url: jdbc:postgresql://223.109.141.69:5432/ai-plat
    username: root
    password: XSJroot123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


auto:
  ops:
    thread:
      pool:
        core-pool-size: 8
        max-pool-size: 16
        queue-capacity: 500
        keep-alive-seconds: 120



